### ISSUE TITLE
Comment's order_id property is nullable

### ISSUE THREAD

**Issue by kakasoo** [figma/rest-api-spec#19]
`Comment`'s order_id is different from the annotation. The annotation says number and the type is written as if it is an optional field, but when I actually wrote the comment and asked for it, both the annotation and the actual type were wrong. This type seems to be number string or null type. Therefore, it should be modified as below.

```typescript
export type Comment = {
  ...
  order_id: `${number}` | null;
  ...
}
```

OR order_id have to be `string | null`.

**Comment by rohitchouhan8** [comment]
Thanks for this! Flagging it internally.

**Comment by figajm** [comment]
Fixed by https://github.com/figma/figma/pull/345550
