### ISSUE TITLE
"containingStateGroup" property missing from types.

### ISSUE THREAD

**Issue by spencerversteeg** [figma/rest-api-spec#7]
`containingStateGroup` is not documented anywhere in the API docs, or types. Missing from [FrameInfo documentation](https://www.figma.com/developers/api#frameinfo-type), as well as in the types.

Another noteworthy mention, is the inconsistent casing in `containing_frame`. The rest of the response values are `snake_case`, while the properties inside `containing_frame` are `camelCase`.

ex:
```
"containing_frame": {
  "name": "Button",
  "nodeId": "10:1360",
  "pageId": "0:1",
  "pageName": "Page 1",
  "backgroundColor": "rgba(0, 0, 0, 0)",
  "containingStateGroup": {
    "name": "Button",
    "nodeId": "10:1360"
  }
}
```

**Comment by james04321** [comment]
Thanks for filing this issue! `containingStateGroup` is intentionally omitted from the documentation as this property was accidentally exposed quite a while back and is not officially supported.

As for inconsistent casing, this is correct -- there are a bunch of other places in the API with inconsistent casing as well. The goal of this project was to document the API as-is and not make any breaking changes to the API itself.
