### ISSUE TITLE
FlowStartingPoint's "name" is listed as a number, when it should be a string

### ISSUE THREAD

**Issue by jsscclr** [figma/rest-api-spec#8]
https://github.com/figma/rest-api-spec/blob/4b7864e84e4251e38cfb2203bf61b18860da0634/openapi/openapi.yaml#L3786-L3799

I'm fairly sure this is an error in the spec, as I get string values when using `name` :)

Thanks!

**Comment by james04321** [comment]
Thanks for reporting this! We'll be fixing this soon.

**Comment by james04321** [comment]
Fixed in 0.13.0: https://github.com/figma/rest-api-spec/pull/10
